using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using RecapApi.Configurations;
using RecapApi.Entities;
using RecapApi.Extensions;

namespace RecapApi.Repositories;

public class RepositoryContext : IdentityDbContext<User>
{
    public RepositoryContext(DbContextOptions<RepositoryContext> options) :
        base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new CompanyConfiguration());
        modelBuilder.ApplyConfiguration(new EmployeeConfiguration());
        modelBuilder.ApplyConfiguration(new RoleConfiguration());
        modelBuilder
            .ConfigureValueGenerator()
            .ConfigureAutoGeneratedProperties<Employee>()
            .ConfigureAutoGeneratedProperties<Company>();
        base.OnModelCreating(modelBuilder);
    }

    public DbSet<Employee>? Employees { get; set; }
    public DbSet<Company>? Companies { get; set; }
}