using Microsoft.EntityFrameworkCore;
using RecapApi.Configurations;
using RecapApi.Entities;
using RecapApi.Extensions;

namespace RecapApi.Repositories;

public class RepositoryContext : DbContext
{
    private readonly IWebHostEnvironment _environment;

    public RepositoryContext(DbContextOptions<RepositoryContext> options, IWebHostEnvironment environment) :
        base(options)
    {
        _environment = environment;
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        if (_environment.IsDevelopment())
        {
            modelBuilder.ApplyConfiguration(new EmployeeConfiguration());
        }

        modelBuilder
            .ConfigureValueGenerator()
            .ConfigureAutoGeneratedProperties<Employee>()
            .ConfigureAutoGeneratedProperties<Company>();
    }

    public DbSet<Employee>? Employees { get; set; }
    public DbSet<Company>? Companies { get; set; }
}