using System.Reflection;
using Microsoft.EntityFrameworkCore;
using RecapApi.Attributes;
using RecapApi.Configurations;
using RecapApi.Entities;
using RecapApi.Extensions;
using RecapApi.ValueGenerators;

namespace RecapApi.DbContexts;

public class ApplicationDbContext : DbContext
{
    private readonly IWebHostEnvironment _environment;

    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options, IWebHostEnvironment environment) :
        base(options)
    {
        _environment = environment;
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        if (_environment.IsDevelopment())
        {
            modelBuilder.ApplyConfiguration(new EmployeeConfiguration());
        }

        modelBuilder
            .ConfigureValueGenerator()
            .ConfigureAutoGeneratedProperties<Employee>()
            .ConfigureAutoGeneratedProperties<Company>();
    }

    public DbSet<Employee>? Employees { get; set; }
}